services:
  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/migo-dl/labelau-frontend:0.3.0a4
    depends_on:
      - service
    ports:
      - "8080:80"

  service:
    image: registry.cn-hangzhou.aliyuncs.com/migo-dl/labelau-service:0.3.0a4
    ports:
      - "3777:3777"
    volumes:
      - ./data-bin:/data-bin
